# -*- coding: utf-8 -*-
"""Train_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdNs071UR40bi5Rz_6Q_4cWxb5feWHNv
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
import joblib
import os

df = pd.read_excel("/content/drive/MyDrive/PROJRCTS ( ML)/ML code/student_activity.xlsx")

X = df.drop(columns=["student_id"])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = IsolationForest(
    n_estimators=300,
    contamination=0.1,
    random_state=42
)

model.fit(X_scaled)

os.makedirs("models", exist_ok=True)

joblib.dump(model, "/content/drive/MyDrive/PROJRCTS ( ML)/ML code/isolation_forest.pkl")
joblib.dump(scaler, "/content/drive/MyDrive/PROJRCTS ( ML)/ML code/scaler.pkl")

print("✅ Training completed")
print("✅ isolation_forest.pkl and scaler.pkl saved")

